### ISSUE TITLE
Running gulp upload every files (watch settings)

### ISSUE THREAD

**Issue by jeffangama** [wictorwilen/gulp-spsync#18]
Hi i tried to setup the gulp watch part, though when i run gulp, it uploads every files instead of watching just the one that changed ? Did i miss smth ?

Thanks

**Comment by jeffangama** [comment]
Think i've found the solution :  
Add watch settings in settings

var settings = {
    "client_id": "xxx",
    "client_secret": "xxx",
    "realm": "",
    "site": "https://xxx.sharepoint.com/sites/xx/",
    "verbose": "true",
    "watch":"true"
};

**Comment by wictorwilen** [comment]
See PR #19
